name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ─────────────────────────────────────  Checkout  ───────────────────────────────────── #
    - uses: actions/checkout@v4

    # ──────────────────────────  Compose-up (postgres, redis, neo4j, seeds)  ────────────── #
    - name: Compose up
      uses: docker/compose-action@v2       # https://github.com/marketplace/actions/docker-compose-action
      with:
        compose-file: docker-compose.yml   # default is ./docker-compose.yml
        up-flags: --build -d               # just like `docker compose up --build -d`
        down-flags: --volumes              # auto-cleanup at job end

    # OPTIONAL: show logs while health-checks settle (handy when debugging)
    - name: Tail container logs (90 s max)
      run: |
        timeout 90s bash -c '
          until docker compose ps | grep "(healthy)"; do
            docker compose ps
            sleep 5
          done'
        docker compose ps
        docker compose logs --tail=50

    # ─────────────────────────────────────  Python & Poetry  ─────────────────────────────── #
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"

    - name: Cache Poetry envs
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          ~/.virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install Poetry
      run: |
        pip install -U pip
        pip install poetry

    - name: Install dependencies
      run: poetry install --with dev

    # ─────────────────────────────────────  Lint & Test  ─────────────────────────────────── #
    - name: Lint & test
      run: |
        poetry run black --check .
        poetry run flake8 .
        poetry run pytest -q --cov=polyfuseql --cov-report=xml

    # ────────────────────────────────  Upload coverage to Codecov  ───────────────────────── #
    - name: Upload coverage
      uses: codecov/codecov-action@v4
